[package]
name = "suins_voting"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet" }

suins_token = { local = "../token" }

[addresses]
suins_voting = "0x0"
