[package]
name = "suins_payments"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move

[dependencies]
suins = { local = "../suins" }
suins_bbb = { local = "../bbb" }

[dependencies.pyth]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-contract-mainnet"

[dependencies.pyth_pro_compatible]
git = "https://github.com/pyth-network/pyth-crosschain.git"
subdir = "target_chains/sui/contracts"
rev = "sui-pro-compatible-contract-mainnet"
rename-from = "pyth"
