version: 2.1

commands:
  setup-sccache:
    steps:
      - run:
          name: Install sccache
          command: |
            cargo install sccache
            sccache --version
  restore-sccache-cache:
    steps:
      - restore_cache:
          name: Restore sccache cache
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
  save-sccache-cache:
    steps:
      - save_cache:
          name: Save sccache cache
          # We use {{ epoch }} to always upload a fresh cache:
          # Of course, restore_cache will not find this exact key,
          # but it will fall back to the closest key (aka the most recent).
          # See https://discuss.circleci.com/t/add-mechanism-to-update-existing-cache-key/9014/13
          key: sccache-cache-stable-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ epoch }}
          paths:
            - "~/.cache/sccache"

jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - setup-sccache
      - restore-sccache-cache
      - run: git clone https://github.com/MystenLabs/sui.git --branch devnet
      - run: sudo apt install libclang-dev
      - run: 
          command: RUSTC_WRAPPER=sccache cargo build --package sui --bin sui
          working_directory: ./sui
      - save-sccache-cache
      - run: ./sui/target/debug/sui move build
      - run: ./sui/target/debug/sui move test --coverage
      - run: ./sui/target/debug/sui move coverage summary --summarize-functions

workflows:
  version: 2
  run-build-and-test:
    jobs:
      - build-and-test
