version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: git clone https://github.com/MystenLabs/sui.git --branch devnet
      - run: sudo apt update
      - run: sudo apt install libclang-dev
      - run: 
          command: cargo build --package sui --bin sui
          working_directory: ./sui
      - run: ./sui/target/debug/sui move build -p ./contracts
      - run: ./sui/target/debug/sui move test -p ./contracts --coverage
      - run: ./sui/target/debug/sui move coverage -p ./contracts summary --summarize-functions

workflows:
  version: 2
  run-build-and-test:
    jobs:
      - build-and-test
