version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: curl -L https://github.com/MystenLabs/sui/releases/download/$TAG/sui > ./contracts/sui_cli
      - run: chmod u+x ./contracts/sui_cli
      - run:
          command: ./sui_cli move build
          working_directory: ./contracts
      - run:
          command: ./sui_cli move test --coverage
          working_directory: ./contracts
      - run:
          command: ./sui_cli move coverage summary --summarize-functions
          working_directory: ./contracts

workflows:
  version: 2
  run_build-and_test:
    jobs:
      - build_and_test
