version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.65.0
    steps:
      - checkout
      - run: curl -L https://github.com/MystenLabs/sui/releases/download/$TAG/sui > /usr/local/bin/sui
      - run: chmod u+x /usr/local/bin/sui
      - run: export PATH=$PATH:/usr/local/bin
      - run:
          command: sui move build
          working_directory: ./contracts
      - run:
          command: sui move test --coverage
          working_directory: ./contracts
      - run:
          command: sui move coverage summary --summarize-functions
          working_directory: ./contracts

workflows:
  version: 2
  run_build-and_test:
    jobs:
      - build_and_test
