[package]
name = "day_one"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override=true }

suins = { local = "../suins" }

[addresses]
day_one = "0x0"
