[package]
name = "discounts"
version = "0.0.1"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet", override=true }
suins = { local = "../suins" }
day_one = { local = "../day_one" }

[addresses]
discounts = "0x0"
