[package]
name = "discounts"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/mainnet", override=true }
suins = { local = "../suins" }
day_one = { local = "../day_one" }

[addresses]
suins_discounts = "0x0"
