[package]
name = "utils"
version = "0.0.1"
edition = "2024.beta"
published-at = "0x42cff5d07eca51e9dcef278c9c3a8b98a0f70f06977868614f6eab1a22d9bd89"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override=true }
suins = { local = "../suins" }


[addresses]
utils = "0x42cff5d07eca51e9dcef278c9c3a8b98a0f70f06977868614f6eab1a22d9bd89"