[package]
name = "suins_bbb"
edition = "2024.beta"

[dependencies]
# Pyth
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet" }
# Aftermath
AftermathAmm = { git = "https://github.com/AftermathFinance/move-interfaces.git", subdir = "packages/amm/amm", rev = "main" }
AfSuiTreasury = { git = "https://github.com/AftermathFinance/move-interfaces.git", subdir = "packages/afsui/afsui-treasury", rev = "main" }
InsuranceFund = { git = "https://github.com/AftermathFinance/move-interfaces.git", subdir = "packages/amm/amm-insurance-fund", rev = "main" }
ProtocolFeeVault = { git = "https://github.com/AftermathFinance/move-interfaces.git", subdir = "packages/amm/amm-protocol-fee-vault", rev = "main" }

[addresses]
suins_bbb = "0x0"
