name: Auto-Assign Reviewers for Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  assign-reviewers:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
