name: Auto-Assign Reviewers and Run pnpm changeset for Dependabot PRs

on:
  pull_request_target:
    types: [opened, synchronize]

jobs:
  run-changeset:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Create changeset file
        run: |
          echo "---" > .changeset/metal-grapes-flow.md
          echo "\"@mysten/suins\": patch" >> .changeset/metal-grapes-flow.md
          echo "---" >> .changeset/metal-grapes-flow.md
          echo "" >> .changeset/metal-grapes-flow.md
          echo "@mysten/sui update" >> .changeset/metal-grapes-flow.md

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push changes
        env:
          PR_HEAD_REF: ${{ github.event.pull_request.head.ref }}
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git add .
          git commit -m "changeset"
          git push origin HEAD:$PR_HEAD_REF

  assign-reviewers:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Assign Reviewers
        uses: kentaro-m/auto-assign-action@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
