name: Move Test CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install Homebrew
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

    - name: Install Sui using Homebrew
      run: brew install sui

    - name: Run Sui Move tests in coupons
      run: sui move test
      working-directory: packages/coupons

    - name: Run Sui Move tests in denylist
      run: sui move test
      working-directory: packages/denylist

    - name: Run Sui Move tests in discounts
      run: sui move test
      working-directory: packages/discounts

    - name: Run Sui Move tests in managed_names
      run: sui move test
      working-directory: packages/managed_names

    - name: Run Sui Move tests in registration
      run: sui move test
      working-directory: packages/registration

    - name: Run Sui Move tests in renewal
      run: sui move test
      working-directory: packages/renewal

    - name: Run Sui Move tests in subdomains
      run: sui move test
      working-directory: packages/subdomains

    - name: Run Sui Move tests in suins
      run: sui move test
      working-directory: packages/suins