name: Move Test CI

on:
  pull_request:
    paths:
      - '.github/workflows/move_test.yml'
      - 'packages/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Add swap memory
        run: |
          sudo fallocate -l 4G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/home/linuxbrew/.linuxbrew/bin" >> $GITHUB_PATH

      - name: Install Sui CLI
        run: |
          brew install sui@1.40.2

      - name: Clear cached dependencies
        run: rm -rf ~/.move

      - name: Run move tests in all package subdirectories, with exclusions
        run: |
          included_dirs=(suins) # Define included directories as an array
          for dir in packages/*; do
            dir_name=$(basename "$dir")
            if [[ " ${included_dirs[*]} " =~ (^|[[:space:]])${dir_name}($|[[:space:]]) ]] && [ -d "$dir" ]; then
              echo "Running sui move test in $dir"
              sui move test --path "$dir"
            fi
          done
