name: SDK Tests CI

on:
  pull_request:
    paths:
      - '.github/workflows/sdk_test.yml'
      - 'sdk/**'
      - 'packages/**'
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  sdk_test:
    name: SDK Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Do a global PNPM install
        run: |
          npm install -g pnpm

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Download & Extract latest SUI binary
        run: |
          url=$(curl -s https://api.github.com/repos/mystenlabs/sui/releases/latest  | jq -r '.assets[] | select(.name | contains("ubuntu")) | .browser_download_url')
          filename="sui-x86-64.tgz"
          wget $url -O $filename
          tar -xzf $filename
          ls
          ./sui -V

      - name: Prepare local network & run SDK tests
        env: 
          IS_CI_JOB: true
        run: |
          export IS_CI_JOB=true && ./sui start --with-faucet --force-regenesis --epoch-duration-ms 300000 > /dev/null 2>&1 & cd sdk && VITE_SUI_BIN="../sui" pnpm test:e2e
